In [62]:
test_words = ["madam", "hello", "Apple", " "]

In [63]:
def is_palindrome(input_string, verbose=False):
    return input_string == input_string[::-1]

for word in test_words:
    print(word, is_palindrome(word))

madam True
hello False
Apple False
  True


In [64]:
def is_palindrome(s, verbose=False):
    if len(s) <= 1: return True
    mid = len(s) // 2
    for i, j in zip(s[:mid], s[mid:][::-1]):
        if i != j:
            return False
    return True

for word in test_words:
    print(f"{word:10}", is_palindrome(word))

madam      True
hello      False
Apple      False
           True


In [79]:
t = [[1,2,3],[4,5,6],[7,8,9]]

def flip_horizontal_axis(matrix):
    return matrix[::-1]

print(t)    
flip_horizontal_axis(t)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


[[7, 8, 9], [4, 5, 6], [1, 2, 3]]

In [78]:
t = [[1,2,3],[4,5,6],[7,8,9]]

def flip_horizontal_axis(matrix):
    #return matrix[::-1]
    for i in range(len(matrix)//2):
        matrix[i], matrix[-i-1] = matrix[-i-1], matrix[i]
  
    return matrix

print(t)    
flip_horizontal_axis(t)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


[[7, 8, 9], [4, 5, 6], [1, 2, 3]]

In [98]:
t = [[1,2,3],[4,5,6],[7,8,9]]

def flip_vertical_axis(matrix):
    return [l[::-1] for l in matrix]
    
print(t)
flip_vertical_axis(t)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


[[3, 2, 1], [6, 5, 4], [9, 8, 7]]

In [99]:
def flip_vertical_axis(matrix):
    
    ans = []
    for row in matrix:
        ans.append(row[::-1])
    return ans

print(t)
flip_vertical_axis(t)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


[[3, 2, 1], [6, 5, 4], [9, 8, 7]]

In [102]:
# modify in place

def flip_vertical_axis(matrix):    
    for i in range(len(matrix)):
        for j in range(len(matrix[i])//2):
            matrix[i][j], matrix[i][-j-1] = matrix[i][-j-1], matrix[i][j]
    return matrix

print(t)
flip_vertical_axis(t)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


[[3, 2, 1], [6, 5, 4], [9, 8, 7]]

# transponse matrix

using `zip`:

In [4]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(matrix)
list(zip(*matrix))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


[(1, 4, 7), (2, 5, 8), (3, 6, 9)]

using numpy:

In [16]:
import numpy as np
print(matrix)
np.transpose(matrix)

[[1, 4, 7], [2, 5, 6], [3, 8, 9]]


array([[1, 2, 3],
       [4, 5, 8],
       [7, 6, 9]])

doing it inplace using python:

In [19]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

def transpose_matrix(matrix):
    for i in range(len(matrix)-1):
        for j in range(i+1, len(matrix[i])):
            matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]
    return matrix

transpose_matrix(matrix)

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]

In [20]:
m = [[1, 0, 1], [1, 0, 1], [1, 0, 1]]
print(np.transpose(m))
print(transpose_matrix(m))

[[1 1 1]
 [0 0 0]
 [1 1 1]]
[[1, 1, 1], [0, 0, 0], [1, 1, 1]]


# find dupes in a list

In [8]:
n = [1, 5, 23, 2, 6, 3, 1, 8, 12, 3]
ans = []
for i in [i for i in n if n.count(i)>1]:
    if i not in ans:
        ans.append(i)
ans

[1, 3]

In [113]:
def duplicate_items(list_numbers):
    list_numbers.sort()
    return [i for i in set(list_numbers) if list_numbers.count(i) > 1]    

duplicate_items(n)

[1, 3]

# Fib

In [118]:
def fib(n):
    if n < 2: 
        return n
    
    return fib(n-1) + fib(n-2)

fib(10) # should be 55

55