some numpy basics

In [2]:
import numpy as np

## making arrays

There are [many ways to make a numpy array](https://devdocs.io/numpy~1.14-array-creation-routines/], so here goes a few I use often:

a random matrix of a given shape:

In [36]:
np.random.rand(3,2)

array([[0.26961883, 0.59833956],
       [0.26282488, 0.42816549],
       [0.85283647, 0.59884275]])

making a filled array:

In [37]:
a = np.full((4,1),1.2)
a

array([[1.2],
       [1.2],
       [1.2],
       [1.2]])

In [53]:
b = np.full((4,4),2)
b

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

making a range of numbers:

In [50]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

changing shapes:

In [90]:
c = np.arange(12).reshape(3,-1)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## broadcasting

now a and b are of different shapes, numpy can broadcast the smaller array so we can still do operations on them:

In [32]:
a + b

array([[3.2, 3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2, 3.2]])

In [33]:
np.dot(b,a)

array([[9.6],
       [9.6],
       [9.6],
       [9.6]])

In [34]:
a * b

array([[2.4, 2.4, 2.4, 2.4],
       [2.4, 2.4, 2.4, 2.4],
       [2.4, 2.4, 2.4, 2.4],
       [2.4, 2.4, 2.4, 2.4]])

## a note on axis

`axis=0` means taker a vertical slice, for example to sum up an array verticaly:

In [91]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [92]:
c.sum(axis=0)

array([12, 15, 18, 21])

`axis=1` is horizontal, so this sums up a matrix horizontally:

In [96]:
c.sum(axis=1)

array([ 6, 22, 38])